common:
  client:
    host: 127.0.0.1
    port: 8201
  server:
    host: 127.0.0.1
    port: 8200
  upload:
    fileSize: 1024*1024*10
    fileWriteDir: /Users/tanxianchen/Downloads/test/
    fileWriteClient: /Users/tanxianchen/Downloads/client/
    fileUploadClient: /Users/tanxianchen/Downloads/